apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-app-deployment
  labels:
    app: reddit-clone-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-clone-app
  template:
    metadata:
      labels:
        app: reddit-clone-app
    spec:
      containers:
        - name: reddit-clone-app
          image: rutvikg/reddit-clone-app:72
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:                # must be inside the container
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
