apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: reddit-clone-app:/Service:argocd/argocd-server
  name: reddit-clone-app-service
  labels:
    app: reddit-clone-app
spec:
  type: LoadBalancer
  selector:
    app: rediit-clone-app
  ports:
    - Port: 80
      targetPort: 3000
